// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web =  FirebaseOptions(
    apiKey: 'AIzaSyDYBc21S3O9dHepvc9pJn3HpgFFJFwzGLQ',
    appId: '1:812369616205:web:5e3f39b712b511a3fd2b04',
    messagingSenderId: '812369616205',
    projectId: 'shopping-app-e0df5',
    authDomain: 'shopping-app-e0df5.firebaseapp.com',
    databaseURL: 'https://shopping-app-e0df5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-e0df5.appspot.com',
  );

  static const FirebaseOptions android =  FirebaseOptions(
    apiKey: 'AIzaSyDf66KixOJn8d7K-PgFQT2wr31bqzhHU0Q',
    appId: '1:812369616205:android:3523ac76c312b5f4fd2b04',
    messagingSenderId: '812369616205',
    projectId: 'shopping-app-e0df5',
    databaseURL: 'https://shopping-app-e0df5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-e0df5.appspot.com',
  );

  static const FirebaseOptions ios =  FirebaseOptions(
    apiKey: 'AIzaSyA6PbASB13MpR78n5cnAdasX5vtO2j1Ttc',
    appId: '1:812369616205:ios:15133f0e7d3d3b40fd2b04',
    messagingSenderId: '812369616205',
    projectId: 'shopping-app-e0df5',
    databaseURL: 'https://shopping-app-e0df5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-e0df5.appspot.com',
    iosBundleId: 'com.example.hackLu',
  );
}
